### PR TITLE
BugFix: automatic scopes with lyfecycles and booleans overlaps with Class methods

### PR DESCRIPTION
**Pull request by tacid**
Problem is if you have a state of Lyfecycle named for example `new` this will overlap a Class method `new` so call of Class.new - will return an Array object! not an Object of Class... same is true for booleans which names may conflict with a Class method names

### CODE REVIEW

**Comment by ddnexus** [comment]
What is the behaviour of the old hobo versions?

**Comment by tacid** [comment]
Don't know... a thing to check

**Comment by tacid** [comment]
I've checkout tag v1.1.0.pre2 and Class.new works without a problems, returns an Object of Class

**Comment by tacid** [comment]
I have to say that error appear in `hobo/lib/hobo/hobo_helper.rb` in `def can_create?` in this particular code:
<code>
     if Hobo.simple_has_many_association?(object)
          object = object.new
          object.set_creator(current_user)
     else
</code>                   

so here in last commits object.new will return array (result of auto scope) when object is has_many association
Example, where I have in has_many associated class Lifecycle with state `new`:

<pre>
 >> InsuranceObject.find(1).orders.new
InsuranceObject Load (0.1ms)   SELECT * FROM `insurance_objects` WHERE (`insurance_objects`.`id` = 1)
Order Load (0.2ms)   SELECT * FROM `orders` WHERE (`orders`.insurance_object_id = 1) AND (orders.state = 'new') 
=> []
</pre>                                                                                                                                                                         


while in hobo 1.1.0.pre2 this code will return Object

**Comment by tacid** [comment]
Yeah! I've got him :)
tacid@c96445d9a130f85e27d5d1ebcfa5655e9cb2e91 
this commit has broken behavior of Object.has_many_association.new

**Comment by ddnexus** [comment]
I am confused: you say that 1.1.0.pre2 is ok, then you pointed a 'broken' commit in that branch. Could you clarify a little, please? :-)

**Comment by tacid** [comment]
What are we talking about just now?

<pre>
commit 29d043522fd594cba414c2cc8a734bf6a6cc2330
Author: Bryan Larsen <bryan@larsen.st>
Date:   Fri Nov 12 21:03:25 2010 -0500

    tag v1.1.0.pre2
</pre>


and commit tacid@c96445d9a130f85e27d5d1ebcfa5655e9cb2e914

<pre>
commit c96445d9a130f85e27d5d1ebcfa5655e9cb2e914
Author: Bryan Larsen <bryan@larsen.st>
Date:   Wed Dec 1 14:33:28 2010 -0500

    [#873] [#839] fix chained scopes and the :include scope.   Credit:
    Matt Jones
</pre>


BUT! what are the sense of checking dates of the commites when the commit  tacid@c96445d9a130f85e27d5d1ebcfa5655e9cb2e914 is found: before this commit Object.has_many_assoc.new returns an object but after it creates array object (result of autoscope new for state `new` in lifecycle, for example) There is removed the check for class `respond_to?` when creating scopes in this patch

**Comment by bryanlarsen** [comment]
Just to clarify:  1.1.0.pre2 works but master does not, right? Would you mind checking to see if 1.1.0.pre0 is broken also?   It seems to me that the only reason that 1.1.0.pre2 works for you is because we've got two bugs masking each other.

This patch is a pretty significant API change, it will never go into 1-0-stable.   Domizio & Matt, what are your opinions on this API change -- can you see any better way to fix it?

**Comment by tacid** [comment]
`git checkout v1.1.0.pre0`
than `./script/console`:

<pre>
>> InsuranceObject.first.orders.new.class.name
 => "Order"
</pre>


`git checkout` c96445d9a130f85e27d5d1ebcfa5655e9cb2e914

and in cosole

<pre>
>>  InsuranceObject.first.orders.new.class.name
  InsuranceObject Load (0.1ms)   SELECT * FROM `insurance_objects` LIMIT 1
  InsuranceObject Columns (1.0ms)   SHOW FIELDS FROM `insurance_objects`
  SQL (1.1ms)   SHOW TABLES
  SQL (0.5ms)   SHOW TABLES
  Order Columns (1.2ms)   SHOW FIELDS FROM `orders`
=> "ActiveRecord::NamedScope::Scope"
</pre>


Where `orders` is `has_many` association in InsuranceObject model

**Comment by tacid** [comment]
I think we do not have to add my patch but fix the c96445d9a130f85e27d5d1ebcfa5655e9cb2e914 commit in that way automatic scopes do not overlap with class methods

**Comment by bryanlarsen** [comment]
Tacid, I'm evaluating your pull requests now re: 1.3.

e298a49 looks like an API change which I'm reluctant to pull.   It's the right thing to do, but it will break apps, so I don't think it's worth pulling.   Luckily Rails3 gives us more options, making this sort of automatic scope less necessary.

the filter-menu stuff is already in 1.3.

575eb00 doesn't apply to 1.3.

Would that be an accurate summary, or did I miss something.

**Comment by tacid** [comment]
That's ok for me. If I will ever need to sort by `assoc.count` I'll do that commit for 1.3 than again :)

**Pull request closed without merging**
