### PR TITLE
FIXES for last version, with some older commits about translation stuff

### PR DESCRIPTION
**Pull request by tacid**
I've found bug in the current tree in file hobo/lib/hobo/lifecycles/transition.rb : fire_event()  was called when change_state(record) returns true, but change_state() has been updated with clear_key stuff and now returns wrong value

I've fixed this

### CODE REVIEW

**Comment by bryanlarsen** [comment]
I've cherry picked the last commit into both 1.1 and 1.0.   Good catch.   I also cherry-picked 3c28320 into 1.1.

Your translation patches seem reasonable (at least the ones I looked at).   Domizio, should I merge them into 1.1?   I imagine you have most of them fixed in 1.3 already with your refactor, although it might be worth looking through them.

**Comment by ddnexus** [comment]
Brian: The I18n has just been refactoried quite a lot, anyway a few changes have been included in the rails3 branch. If you want to merge them, it's up to you, anyway the 1.1 branch is not really internationalized without the i18n branch, but I am not sure that merging i18n into 1.1 is worth the effort, because the rails3 include and improve i18n.

Tacid: could you give a try to the 1.3 with respect to i18n?

**Comment by tacid** [comment]
> Tacid: could you give a try to the 1.3 with respect to i18n?

ddnexus: my new project uses hobo 1.3 so in the future I'll be focused on 1.3 branch

**Comment by tacid** [comment]
#### Last 3 commits:

## 1

tacid@55bee3e86029cd1985ab2a48df84b8db672e2e51 : order_by now can be used with has_many_assoc.count. For example in controller U can use now

```
def index 
    hobo_index Category.apply_scope(:order_by => parse_sort_param("name", "stories.count"))
end 
```

when the "stories" is has_many association in Category model

## 2

tacid@c4e768d51f961282faddfbbb92aa02518f8648b7 : filter-menu tag incorectly sets "selected=" when options is array of [opt_name, opt_value], like

options = [["Option1", 1], ["Option2", 2], ["Option3", 3], ["Option4", 4]] 
while select-menu tag works with such an options array

## 3

tacid@0f55bab768bf3c90e1738f4aead7581db5d01c59 

in order_by auto scope added support for many to many associations (count) sortinging with through, for example:

Category model:
    class Category < ActiveRecord::Base
        hobo_model 
        fields do
           name :string, :required, :unique
           timestamps
        end

```
    has_many :posts, :through => :category_assignments
    has_many :category_assignments, :dependent => :destroy               

    # --- Permissions --- #
      # SKIPPED #
end
```

CategoryAssigment model:
    class CategoryAssigment < ActiveRecord::Base
        hobo_model 
        fields do
           timestamps
        end

```
    belongs_to :post
    belongs_to :category

    # --- Permissions --- #
      # SKIPPED #
end
```

Post model:
    class Post < ActiveRecord::Base
        hobo_model 
        fields do
           title :string, :required, :unique
           content :text
           timestamps
        end

```
    has_many :categories, :through => :category_assignments
    has_many :category_assignments, :dependent => :destroy               

    # --- Permissions --- #
      # SKIPPED #
end
```

So Post.order_by('categories.count','asc') will generate SQL

```
 SELECT * FROM `posts` ORDER BY (SELECT count(*) AS count_all FROM `categories` INNER JOIN `category_assignments` ON `category_assignments`.category_id = `categories`.id WHERE `category_assignments`.post_id = `posts`.id ) ASC
```

**Comment by bryanlarsen** [comment]
Tacid,

Your i18n patches caused a failure in https://github.com/tablatom/agility/blob/master/test/integration/foos_basic_test.rb line 38.   It returns "April 08" rather than "April  8".   We don't explicitly define a date format.

I'm tempted just to "fix the test", or are you surprised this happened?

**Comment by tacid** [comment]
I think this is connected with locale default date format :long

**Pull request merged**
